services:
  products-mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: products-mongo
    ports: 
      - "27020:27020"
    command: ["mongod", "--port", "27020"]
    volumes:
      - mongo-products-data:/data/db
    networks:
      - kitchenwares-network
  
  images-mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: images-mongo
    ports:
      - "27021:27021"
    command: [ "mongod", "--port", "27021" ]
    volumes:
      - mongo-images-data:/data/db
    networks:
      - kitchenwares-network
  
  products-service:
    container_name: products-service
    image: jasonjonathan69/kitchenwares-products:latest
    build:
      context: .
      dockerfile: "Kitchenwares Products/Dockerfile"
    depends_on: 
      - products-mongo
    networks: 
      - kitchenwares-network
    ports:
      - "8002:8080"
  
  images-service:
    container_name: images-service
    image: jasonjonathan69/kitchenwares-images:latest
    build:
      context: .
      dockerfile: "KitchenwaresImages/Dockerfile"
    depends_on: 
      - images-mongo
    networks: 
      - kitchenwares-network
    ports:
      - "8003:8080"
  
  auth-service:
    container_name: auth-service
    image: jasonjonathan69/kitchenwares-auth:latest
    build:
      context: .
      dockerfile: "KitchenwaresAuth/Dockerfile"
    networks: 
      - kitchenwares-network
    ports:
      - "8004:8080"
  
  kitchenwares-gateway:
    container_name: kitchenwares-gateway
    image: jasonjonathan69/kitchenwares-gateway:latest
    build:
      context: ./KitchenwaresGateway
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    networks: 
      - kitchenwares-network

networks:
  kitchenwares-network:
    driver: bridge
    
volumes: 
  mongo-products-data:
  mongo-images-data: