services:
  products-mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: products-mongo
    ports: 
      - "27020:27020"
    command: ["mongod", "--port", "27020"]
    volumes:
      - mongo-products-data:/data/db
    networks:
      - kitchenwares-network
  
  images-mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: images-mongo
    ports:
      - "27021:27021"
    command: [ "mongod", "--port", "27021" ]
    volumes:
      - mongo-images-data:/data/db
    networks:
      - kitchenwares-network
        
  auth-mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: auth-mongo
    ports:
      - "27022:27022"
    command: [ "mongod", "--port", "27022" ]
    volumes:
      - mongo-auth-data:/data/db
    networks:
      - kitchenwares-network
  
  products-service:
    container_name: products-service
    image: jasonjonathan69/kitchenwares-products:latest
    build:
      context: .
      dockerfile: "Kitchenwares Products/Dockerfile"
    depends_on: 
      - products-mongo
    networks: 
      - kitchenwares-network
    ports:
      - "8002:8080"
    environment:
      - Jwt:Issuer=http://localhost:8004
      - Jwt:Audience=http://localhost:8001
      - Jwt:SecretKey=kjAFhnm123AhqweiouKJSDU4187LKJNZXCB
      - Db:ConnectionString=mongodb://products-mongo:27020
      - Db:CollectionName=kitchenwares
      - Db:DatabaseName=products
  
  images-service:
    container_name: images-service
    image: jasonjonathan69/kitchenwares-images:latest
    build:
      context: .
      dockerfile: "KitchenwaresImages/Dockerfile"
    depends_on: 
      - images-mongo
    networks: 
      - kitchenwares-network
    ports:
      - "8003:8080"
  
  auth-service:
    container_name: auth-service
    image: jasonjonathan69/kitchenwares-auth:latest
    build:
      context: .
      dockerfile: "KitchenwaresAuth/Dockerfile"
    networks: 
      - kitchenwares-network
    ports:
      - "8004:8080"
    environment:
      - Jwt:Issuer=http://localhost:8004
      - Jwt:Audience=http://localhost:8001
      - Jwt:SecretKey=kjAFhnm123AhqweiouKJSDU4187LKJNZXCB
      - Jwt:ExpirationInMinutes=60
      - Db:ConnectionString=mongodb://auth-mongo:27022
      - Db:CollectionName=kitchenwares
      - Db:DatabaseName=auth
  
  kitchenwares-gateway:
    container_name: kitchenwares-gateway
    image: jasonjonathan69/kitchenwares-gateway:latest
    build:
      context: .
      dockerfile: "KitchenwaresGateway/Dockerfile"
    ports:
      - "8001:8080"
    networks: 
      - kitchenwares-network

networks:
  kitchenwares-network:
    driver: bridge
    
volumes: 
  mongo-products-data:
  mongo-images-data:
  mongo-auth-data: